### ISSUE TITLE
How to resolve this error ：ImportError: cannot import name 'yaml_load' from 'utils.general' (C:\Users\Administrator\Desktop\AIMBOT\rootkit\AI-Aimbot-main\utils\general.py)

### ISSUE THREAD

**Issue by sinshock** [RootKit-Org/AI-Aimbot#25]

**Comment by emohkam** [comment]
Interesting, I faced the same Issue. It might be a version inconsistancy. Apparently general.py file does not include a yaml_loader which is requested by Yolov5 (models/common.py) after downloading into cache. I tried to pass it and found also another import errors, like the 'smart_inference_mode' from 'utils.torch_utils'. Must be a version inconsistancy.

**Comment by Qfc9** [comment]
It's an issue because I copied Yolov5 Dependencies directly into our repo because there isn't a pypi version of it available. So this is an our bad. Ill patch it this weekend unless someone else want's to submit a PR before then. You will receive the Champion role in discord, which is standard whenever someone supports us non-monetarily.

**Comment by H3lix-Fire** [comment]
Just download https://github.com/ultralytics/yolov5 and paste all the utils over, fixes everything for me.

**Comment by Qfc9** [comment]
@H3lix-Fire If you make a PR with the update material, ill pull it in

**Comment by Qfc9** [comment]
No one submitted a PR, so I did it myself
