### ISSUE TITLE
When there are many people on the screen, the screen will shake among many people.

### ISSUE THREAD

**Issue by AnnSir233** [RootKit-Org/AI-Aimbot#26]
First of all, thank you very much for updating this project. 
The performance improvement this time is extremely obvious. 
However, there are still some problems in the process of using and debugging.
For example, when there are two people in the picture, the collimator will constantly swing between the first person and the second person. 
In order to avoid this, a judgment should be added: always take the one with the largest box_size in the picture as the target.

**Comment by Qfc9** [comment]
Agreed. It's because of the combo between decision making logic and the slight differences of the bounding boxes being drawn around humanoid objects.

The logic right now will move the mouse to the closest humanoid object at the center of the screen using basic logic. It has no robust logic of memory or discernment between people right now.

Going with largest box size is a way to normalize it. You are free to send a PR with additional code. If anything, I would make it into an "aim mode" where they can choose between the default and the "large box" mode.
