### ISSUE TITLE
package issue

### ISSUE THREAD

**Issue by LiteEagle262** [RootKit-Org/AI-Aimbot#48]
hello, im getting the following error

``` Traceback (most recent call last):
  File "C:\Users\ayden\OneDrive\Desktop\AI-Aimbot-2.2.2\AI-Aimbot-2.2.2\main.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

ive re installed the module multiple times  and it has still  not worked please help.

**Comment by Franx245** [comment]
The error you are receiving indicates that the "torch" module has not been found. This can be due to various reasons, some of which include:

The main.py file is in a location different from the environment where PyTorch was installed. Make sure you are running your script from the environment where PyTorch was installed.
 Make sure your Python environment is configured correctly to look for modules in the PyTorch installation path.

I recommend you to completely uninstall all PyTorch packages and reinstall them, and write the correct PATH for Torch in case you are using a Windows system.

Additionally, you should also make sure you have the correct version of Pytorch installed (either CPU or GPU version) and according to your operating system (win32 or win_amd64) and python version (27 or 37)
For example, if you have a 64-bit Windows operating system and python 3.7, you should install the version:

`torch-1.6.0+cpu-cp37-cp37m-win_amd64.whl`

**Comment by Qfc9** [comment]
Follow instructions
