### ISSUE TITLE
Cupy errors on AMD gpu for Windows 10

### ISSUE THREAD

**Issue by ElPuebloLoco** [RootKit-Org/AI-Aimbot#62]
Hi, I have errors with cupy on amd gpu. It says "no cuda capable device is detected". Which is obvious, I don't have Nvidia GPU. How can I solve ? Is there a version of cupy for AMD ? (maybe cupy-rocm, but I'm on Windows 10 and it says it's only for Linux). How can I solve ?

**Comment by Villageslayer** [comment]
Check the PRs I already Fixed it

**Comment by Allmight0000** [comment]
> Check the PRs I already Fixed it

I'M HAVING THE SAME ERROR HOW DID YOU SOLVE IT?

**Comment by ayetristan** [comment]
make sure you install cupy using pip from command prompt, it has to support the version of cuda you have, 

use this link:

https://docs.cupy.dev/en/stable/install.html

go through all the steps carefully and ready to run the program, instead of running "python main.py"

you are going to run "pip install onnxruntime" then when thats finish, run "python  main_onnx_cpu.py" as this will initiate the amd version

**Comment by Qfc9** [comment]
There is an Nvidia version now

**Comment by Qfc9** [comment]
Amd version now*
