### ISSUE TITLE
yolov8 TRT version

### ISSUE THREAD

**Issue by voxupe** [RootKit-Org/AI-Aimbot#64]
Do you have any plans to implement a yolov8 TensorRT version for this project？

**Comment by AdamRoden** [comment]
@voxupe If you look at my code here: a073a3489b407ca5b4c8615af5365b9c3350e53f you can see the changes necessary to use yolov8. If you have TensorRT setup you can use yolo from a command prompt to convert a pt file to an engine file and model using TensorRT.

**Comment by voxupe** [comment]
> @voxupe If you look at my code here: [38d601f](https://github.com/RootKit-Org/AI-Aimbot/commit/38d601f4eccde7cec00b4f9f71dea40a76cfec3a) you can see the changes necessary to use yolov8. If you have TensorRT setup you can use yolo from a command prompt to convert a pt file to an engine file using: `yolo export model=yolov8s.pt format=engine device=0`

Confirmed.
thank u for implement this.
I've created my V8 version aimbot now.

**Comment by chowtyme** [comment]
Alright, I'm incredibly stuck here. I've tried various methods to build the prelearned pt model engine, but I am getting errors left and right. I've tried the latest CUDA version (and others) alongside CUDNN & TensorRT versions. Latest one I've tried is CUDNN 8.8.1.3 & TensorRT 8.6.0 (CP310) for CUDA 12. I am noticing I am getting consistent failures with it converting to onnx, mostly with almost every build module. Anyone have any pointers, or insight? I'm learning as much as I can.

**Comment by AdamRoden** [comment]
@chowtyme I know what you are going through. The versions of Python, CUDA, ONNX, etc. all matter and if you try to use the newest versions you are going to have a bad time. Here's what I suggest:

- Uninstall all the CUDA stuff and start with a clean slate.
- Install Anaconda and use it to manage your python environments.
- With Anaconda Navigator, create a Python v3.10 environment. (3.11 has incompatibilities)
- Next, use Anaconda Prompt to do things like activate your env, and install packages. (conda activate [myvenv]), (pip install -r requirements.txt)
- If you are unsure of what versions work, you can open Ultralytics's colab and run pip list. Here's a link: https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb
- Regarding the CUDA Toolkit, you need to install v11.7 because it is the newest version Ultralytics will accept.
- Likewise, PyTorch v2.0 will probably not work, you need v1.13.1cuXXX

**Comment by voxupe** [comment]
> To be honest in FPS gaming, yolov8 does not have much improve in inferring, also it is slower

For consumer graphics cards， indeed.
On a100, v8 has amazing performance

**Comment by AdamRoden** [comment]
@AI-M-BOT @voxupe 
I'm curious about the hardware, image sources and sizes, and prediction confidences used to arrive at your conclusions. I didn't keep a record of performance results, but switching back and forth I felt that the v8 small model gave the best combination of speed and confidence. Keeping in mind that performance varies if you are testing against a scrolling browser window, a recorded video, or an active game stream.

On the other hand, regarding PyTorch vs TensorRT, there are claims that TensorRT can be 2x or even 6x faster, but in my tests it only ever increased performance by 35-45% across all yolov8 test scenarios.

**Comment by AdamRoden** [comment]
@AI-M-BOT @voxupe 
I agree on paper there is not a large significant difference between v5 and v8. I didn't keep a record of performance results, but switching back and forth I felt that the v8 small model gave the best combination of speed and confidence. Keeping in mind that performance varies if you are testing against a scrolling browser window, a recorded video, or an active game stream.

I'm curious about the hardware, image sources and sizes, and prediction confidences used to arrive at your conclusions. 

In regards PyTorch vs TensorRT, there are claims that TensorRT can be 2x or even 6x faster, but in my tests it only ever increased performance by 35-45% across all yolov8 test scenarios.

**Comment by Qfc9** [comment]
Y'all are free to submit a PR for v8 version of it. I will continue to advise not using it to people unless they have a high end card.
