### ISSUE TITLE
Mouse just flies all over the place, other issues as well

### ISSUE THREAD

**Issue by jcrawl16** [RootKit-Org/AI-Aimbot#73]
I tried using main.py, I got a "no module found" error so I ended up having to pip install a whole bunch of different modules before it finally worked, or at least I thought it did. When I actually got into game (Overwatch, also tested Fortnite with the 3rd person setting enabled), the mouse just bounced around at random. I tried to see what was going wrong by turning on the visuals setting, but that gave me an error I couldn't understand, something overload resolution.  So, I tried restarting my computer, then used main.py again, this time all of the sudden it says torch not compiled with CUDA enabled. Which is strange because according to nvcc --version I have CUDA 11.7 installed, and I double checked to make sure I installed the correct pytorch as well, also using Python 3.10, and I have an RTX 2060.  Anyway, I gave up on main.py and tried all the other ones as well, the only one that didn't give me an error is the onnxruntime cpu, but again, that one just makes my mouse fly in random directions just like main.py did.

**Comment by adb1042** [comment]
(Im not part of the dev team) I have been looking into the mouse flying everywhere issue for a minute, what i think the issue stems from is that the absolute center of the window is not always where the mouse is centered in FPS games. typically the mouse is a little lower and to the left / right a bit. If you delve into the code on how it works. it basically follows these steps. 

1. take screenshot
2. check for human at X% confidence level
3. if met, draw a box around it (you can see the box with visuals turned on) 
4.if headshot mode turned on, move the mouse torwards the middle top of the box, (typically where heads are) 
5. if not, move towards the center of the box. 
6. keep repeating steps 1-4 or 1-5 until 3 is no longer met. (when ai has lost track of the target, stop) 


the issue is, if the mouse is ever so slightly off center of the absolute center of the window, the mouse will NEVER reach the center of the box, as the program is telling the mouse to move torwards the box in respect to the absolute center of the window, not the center based on the mouse's position. 

As far as how to fix this issue, i've got no clue, but i am working on a solution atm
