### ISSUE TITLE
pls make the HOLD mode, not toggle, pls =3

### ISSUE THREAD

**Issue by meowsynth** [RootKit-Org/AI-Aimbot#91]

**Comment by meowsynth** [comment]
title

**Comment by skhrlx** [comment]
if win32api.GetAsyncKeyState(0x01):
This prob will work for you since I'm don't downloaded and tested the project yet, and I'm not on home
Just search for GetAsyncKeyState on the code, and add "Async".

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate
